import type { Metadata } from "next";

export const metadata: Metadata = { title: "Insights | IM Attorneys Pretoria", description: "Clear, practical legal guidance from IM Attorneys in Pretoria." };

const articles = [
  { category: "Family law", title: "Before a family-law matter becomes a crisis: the value of early legal clarity.", copy: "When family circumstances change, decisions about children, maintenance, safety and shared property can feel immediate. Understanding the legal position early helps clients protect what matters before pressure decides the next move.", read: "4 min read", accent: "Family & matrimonial law" },
  { category: "Criminal defence", title: "After an arrest: why prompt, calm legal guidance matters.", copy: "An arrest can be disorientating for the person involved and their family. Early legal assistance helps clarify the immediate position, protect rights and prepare the next court step without avoidable delay.", read: "3 min read", accent: "24/7 bail assistance" },
  { category: "Commercial counsel", title: "A contract is not just paperwork—it is a business decision in writing.", copy: "Before signing, cancelling or responding to a contract, the legal and commercial consequences deserve careful attention. A clear review can expose risk, protect relationships and support better decisions.", read: "5 min read", accent: "Commercial contracts" },
  { category: "Estates & legacy", title: "What a considered will can give the people you love.", copy: "Estate planning is an opportunity to make wishes clear, reduce uncertainty and leave a more orderly path for the people who may one day need to act on your behalf.", read: "4 min read", accent: "Wills & estates" },
];

export default function InsightsPage() {
  return <main className="editorial-page insights-page">
    <header className="editorial-header"><a href="/" className="editorial-brand editorial-brand-logo"><img src="https://im-attorneys.gee7pipz.chatgpt.site/assets/im-attorneys-incorporated-logo.webp" alt="Ingrid Mtsweni Attorneys Incorporated" width={1200} height={400} /></a><nav><a href="/#expertise">Practice areas</a><a href="/about">About the firm</a><a className="editorial-header-cta" href="/contact">Contact the firm</a></nav></header>
    <section className="insights-hero"><span className="editorial-kicker">IM Attorneys Insights</span><h1>Legal clarity for the questions that matter <em>before</em> they become urgent.</h1><p>Practical, plain-language guidance for people and businesses navigating important legal decisions. These insights are a starting point for understanding—not a substitute for advice on your specific matter.</p><div><span>PRETORIA · SOUTH AFRICA</span><span>Clear guidance · Purposeful action</span></div></section>
    <section className="insights-feature"><div><span>Featured guidance</span><h2>When should you speak to an attorney?</h2><p>Not every problem begins in a courtroom. The right time to seek advice is often before signing, responding, agreeing, escalating or waiting for a deadline to decide the matter for you.</p><a href="/contact">Discuss your situation <b>→</b></a></div><aside><small>IM / 01</small><strong>Clarity before pressure.</strong><p>Family. Freedom. Legacy. Business. The earlier the legal position is understood, the more options may remain available.</p></aside></section>
    <section className="insights-list"><div className="editorial-section-heading"><span>In focus</span><h2>Guidance for life and business.</h2><p>Start with the topic closest to your situation, then speak to the firm for advice shaped around your actual circumstances.</p></div><div className="insights-grid">{articles.map((article, index) => <article key={article.title}><div><small>{String(index + 1).padStart(2, "0")}</small><span>{article.category}</span></div><h3>{article.title}</h3><p>{article.copy}</p><footer><span>{article.read} · {article.accent}</span><a href="/contact" aria-label={`Discuss ${article.category} with IM Attorneys`}>→</a></footer></article>)}</div></section>
    <section className="insights-disclaimer"><span>Important note</span><h2>Information is useful. Personal legal advice is different.</h2><p>The content on this page is general guidance. Your rights, risks, deadlines and options depend on the specific facts of your matter. A confidential consultation gives the firm an opportunity to understand those facts before advising you.</p><a href="/contact">Book a consultation <b>→</b></a></section>
    <footer className="editorial-footer"><a href="/" className="editorial-footer-logo"><img src="https://im-attorneys.gee7pipz.chatgpt.site/assets/im-attorneys-incorporated-logo.webp" alt="Ingrid Mtsweni Attorneys Incorporated" width={1200} height={400} /></a><span>Information on this website is general and does not constitute legal advice.</span><a href="/contact">Speak to the firm</a></footer>
  </main>;
}
